data = {
    "HasOverlay": true,
    "Lines": [
       {
        "MaxHeight": 49,
        "MinTop": 172,
        "Words":  [
           {
            "Height": 49,
            "Left": 2662,
            "Top": 172,
            "Width": 66,
            "WordText": "23",
          },
        ],
      },
       {
        "MaxHeight": 69,
        "MinTop": 377,
        "Words":  [
           {
            "Height": 60,
            "Left": 296,
            "Top": 388,
            "Width": 63,
            "WordText": "F):",
          },
           {
            "Height": 61,
            "Left": 382,
            "Top": 385,
            "Width": 152,
            "WordText": "'C,ept,",
          },
           {
            "Height": 49,
            "Left": 558,
            "Top": 380,
            "Width": 10,
            "WordText": "i",
          },
           {
            "Height": 54,
            "Left": 592,
            "Top": 378,
            "Width": 144,
            "WordText": "don't",
          },
           {
            "Height": 56,
            "Left": 757,
            "Top": 377,
            "Width": 147,
            "WordText": "think",
          },
           {
            "Height": 65,
            "Left": 924,
            "Top": 383,
            "Width": 108,
            "WordText": "Gup",
          },
           {
            "Height": 55,
            "Left": 1055,
            "Top": 381,
            "Width": 215,
            "WordText": "realizes",
          },
           {
            "Height": 53,
            "Left": 1293,
            "Top": 383,
            "Width": 120,
            "WordText": "how",
          },
           {
            "Height": 53,
            "Left": 1436,
            "Top": 386,
            "Width": 99,
            "WordText": "bad",
          },
           {
            "Height": 49,
            "Left": 1560,
            "Top": 391,
            "Width": 32,
            "WordText": "it",
          },
           {
            "Height": 48,
            "Left": 1617,
            "Top": 392,
            "Width": 40,
            "WordText": "is",
          },
           {
            "Height": 55,
            "Left": 1675,
            "Top": 399,
            "Width": 101,
            "WordText": "yet.",
          },
           {
            "Height": 47,
            "Left": 1836,
            "Top": 407,
            "Width": 167,
            "WordText": "tncal),",
          },
           {
            "Height": 69,
            "Left": 2025,
            "Top": 394,
            "Width": 211,
            "WordText": "looking",
          },
           {
            "Height": 48,
            "Left": 2259,
            "Top": 400,
            "Width": 46,
            "WordText": "in",
          },
           {
            "Height": 50,
            "Left": 2432,
            "Top": 413,
            "Width": 123,
            "WordText": "cycr,",
          },
           {
            "Height": 50,
            "Left": 2578,
            "Top": 399,
            "Width": 12,
            "WordText": "I",
          },
        ],
      },
       {
        "MaxHeight": 54,
        "MinTop": 488,
        "Words":  [
           {
            "Height": 54,
            "Left": 291,
            "Top": 488,
            "Width": 157,
            "WordText": "don'ts",
          },
        ],
      },
       {
        "MaxHeight": 66,
        "MinTop": 664,
        "Words":  [
           {
            "Height": 49,
            "Left": 292,
            "Top": 668,
            "Width": 172,
            "WordText": "LANE:",
          },
           {
            "Height": 66,
            "Left": 489,
            "Top": 665,
            "Width": 266,
            "WordText": "Nothing's",
          },
           {
            "Height": 37,
            "Left": 777,
            "Top": 680,
            "Width": 123,
            "WordText": "ever",
          },
           {
            "Height": 62,
            "Left": 916,
            "Top": 669,
            "Width": 155,
            "WordText": "going",
          },
           {
            "Height": 43,
            "Left": 1091,
            "Top": 675,
            "Width": 52,
            "WordText": "to",
          },
           {
            "Height": 54,
            "Left": 1163,
            "Top": 664,
            "Width": 64,
            "WordText": "be",
          },
           {
            "Height": 52,
            "Left": 1249,
            "Top": 667,
            "Width": 87,
            "WordText": "the",
          },
           {
            "Height": 46,
            "Left": 1528,
            "Top": 673,
            "Width": 9,
            "WordText": "f",
          },
        ],
      },
       {
        "MaxHeight": 63,
        "MinTop": 840,
        "Words":  [
           {
            "Height": 49,
            "Left": 291,
            "Top": 846,
            "Width": 213,
            "WordText": "PORKY:",
          },
           {
            "Height": 60,
            "Left": 529,
            "Top": 845,
            "Width": 184,
            "WordText": "Except",
          },
           {
            "Height": 36,
            "Left": 736,
            "Top": 856,
            "Width": 71,
            "WordText": "us.",
          },
           {
            "Height": 52,
            "Left": 828,
            "Top": 840,
            "Width": 164,
            "WordText": "VVcere",
          },
           {
            "Height": 63,
            "Left": 1011,
            "Top": 844,
            "Width": 155,
            "WordText": "going",
          },
           {
            "Height": 42,
            "Left": 1186,
            "Top": 851,
            "Width": 54,
            "WordText": "to",
          },
           {
            "Height": 52,
            "Left": 1260,
            "Top": 841,
            "Width": 65,
            "WordText": "be",
          },
           {
            "Height": 50,
            "Left": 1347,
            "Top": 843,
            "Width": 87,
            "WordText": "the",
          },
           {
            "Height": 36,
            "Left": 1456,
            "Top": 859,
            "Width": 161,
            "WordText": "Gallic.",
          },
           {
            "Height": 49,
            "Left": 1641,
            "Top": 848,
            "Width": 95,
            "WordText": "But",
          },
           {
            "Height": 55,
            "Left": 1756,
            "Top": 847,
            "Width": 187,
            "WordText": "better.",
          },
        ],
      },
       {
        "MaxHeight": 60,
        "MinTop": 1017,
        "Words":  [
           {
            "Height": 60,
            "Left": 288,
            "Top": 1020,
            "Width": 64,
            "WordText": "F):",
          },
           {
            "Height": 47,
            "Left": 377,
            "Top": 1021,
            "Width": 94,
            "WordText": "Fov",
          },
           {
            "Height": 49,
            "Left": 491,
            "Top": 1017,
            "Width": 117,
            "WordText": "hill).",
          },
        ],
      },
       {
        "MaxHeight": 64,
        "MinTop": 1191,
        "Words":  [
           {
            "Height": 49,
            "Left": 283,
            "Top": 1193,
            "Width": 199,
            "WordText": "BRIAN:",
          },
           {
            "Height": 46,
            "Left": 509,
            "Top": 1194,
            "Width": 160,
            "WordText": "Dainn",
          },
           {
            "Height": 64,
            "Left": 692,
            "Top": 1191,
            "Width": 220,
            "WordText": "straight",
          },
           {
            "Height": 49,
            "Left": 929,
            "Top": 1191,
            "Width": 186,
            "WordText": "better.",
          },
        ],
      },
       {
        "MaxHeight": 61,
        "MinTop": 1364,
        "Words":  [
           {
            "Height": 60,
            "Left": 280,
            "Top": 1368,
            "Width": 64,
            "WordText": "F):",
          },
           {
            "Height": 50,
            "Left": 365,
            "Top": 1367,
            "Width": 150,
            "WordText": "Yeah.",
          },
           {
            "Height": 61,
            "Left": 535,
            "Top": 1367,
            "Width": 140,
            "WordText": "They",
          },
           {
            "Height": 51,
            "Left": 694,
            "Top": 1365,
            "Width": 144,
            "WordText": "don't",
          },
           {
            "Height": 55,
            "Left": 858,
            "Top": 1364,
            "Width": 189,
            "WordText": "realize",
          },
           {
            "Height": 54,
            "Left": 1067,
            "Top": 1367,
            "Width": 110,
            "WordText": "he's",
          },
           {
            "Height": 59,
            "Left": 1197,
            "Top": 1377,
            "Width": 90,
            "WordText": "got",
          },
           {
            "Height": 36,
            "Left": 1308,
            "Top": 1387,
            "Width": 76,
            "WordText": "us.",
          },
        ],
      },
       {
        "MaxHeight": 62,
        "MinTop": 1543,
        "Words":  [
           {
            "Height": 47,
            "Left": 281,
            "Top": 1545,
            "Width": 109,
            "WordText": "LAN",
          },
           {
            "Height": 47,
            "Left": 403,
            "Top": 1545,
            "Width": 45,
            "WordText": "E:",
          },
           {
            "Height": 53,
            "Left": 474,
            "Top": 1545,
            "Width": 85,
            "WordText": "No,",
          },
           {
            "Height": 62,
            "Left": 581,
            "Top": 1543,
            "Width": 119,
            "WordText": "they",
          },
           {
            "Height": 50,
            "Left": 722,
            "Top": 1543,
            "Width": 158,
            "WordText": "don't.",
          },
        ],
      },
       {
        "MaxHeight": 49,
        "MinTop": 1718,
        "Words":  [
           {
            "Height": 47,
            "Left": 279,
            "Top": 1720,
            "Width": 126,
            "WordText": "KAT:",
          },
           {
            "Height": 48,
            "Left": 432,
            "Top": 1720,
            "Width": 96,
            "WordText": "Not",
          },
           {
            "Height": 40,
            "Left": 547,
            "Top": 1728,
            "Width": 50,
            "WordText": "at",
          },
           {
            "Height": 49,
            "Left": 617,
            "Top": 1718,
            "Width": 78,
            "WordText": "all.",
          },
        ],
      },
       {
        "MaxHeight": 63,
        "MinTop": 1894,
        "Words":  [
           {
            "Height": 57,
            "Left": 275,
            "Top": 1896,
            "Width": 196,
            "WordText": "JIMMY:",
          },
           {
            "Height": 63,
            "Left": 491,
            "Top": 1894,
            "Width": 216,
            "WordText": "They're",
          },
           {
            "Height": 48,
            "Left": 725,
            "Top": 1911,
            "Width": 188,
            "WordText": "gonna.",
          },
        ],
      },
       {
        "MaxHeight": 50,
        "MinTop": 2069,
        "Words":  [
           {
            "Height": 50,
            "Left": 278,
            "Top": 2069,
            "Width": 228,
            "WordText": "DEBBIE:",
          },
        ],
      },
       {
        "MaxHeight": 47,
        "MinTop": 2073,
        "Words":  [
           {
            "Height": 47,
            "Left": 531,
            "Top": 2073,
            "Width": 92,
            "WordText": "For",
          },
           {
            "Height": 36,
            "Left": 641,
            "Top": 2087,
            "Width": 135,
            "WordText": "sure.",
          },
        ],
      },
       {
        "MaxHeight": 64,
        "MinTop": 2242,
        "Words":  [
           {
            "Height": 55,
            "Left": 279,
            "Top": 2242,
            "Width": 236,
            "WordText": "JOANNE:",
          },
           {
            "Height": 64,
            "Left": 538,
            "Top": 2248,
            "Width": 208,
            "WordText": "Totally.",
          },
        ],
      },
       {
        "MaxHeight": 63,
        "MinTop": 2414,
        "Words":  [
           {
            "Height": 52,
            "Left": 275,
            "Top": 2414,
            "Width": 237,
            "WordText": "TAMMY:",
          },
           {
            "Height": 63,
            "Left": 533,
            "Top": 2421,
            "Width": 188,
            "WordText": "Cherry",
          },
           {
            "Height": 33,
            "Left": 741,
            "Top": 2439,
            "Width": 66,
            "WordText": "on",
          },
           {
            "Height": 60,
            "Left": 828,
            "Top": 2428,
            "Width": 108,
            "WordText": "top!",
          },
        ],
      },
       {
        "MaxHeight": 65,
        "MinTop": 2586,
        "Words":  [
           {
            "Height": 60,
            "Left": 280,
            "Top": 2586,
            "Width": 62,
            "WordText": "FJ:",
          },
           {
            "Height": 48,
            "Left": 366,
            "Top": 2589,
            "Width": 114,
            "WordText": "Deal",
          },
           {
            "Height": 41,
            "Left": 504,
            "Top": 2606,
            "Width": 54,
            "WordText": "is,",
          },
           {
            "Height": 46,
            "Left": 576,
            "Top": 2608,
            "Width": 100,
            "WordText": "you",
          },
           {
            "Height": 58,
            "Left": 700,
            "Top": 2598,
            "Width": 199,
            "WordText": "realize,",
          },
           {
            "Height": 37,
            "Left": 917,
            "Top": 2616,
            "Width": 131,
            "WordText": "once",
          },
           {
            "Height": 51,
            "Left": 1068,
            "Top": 2605,
            "Width": 109,
            "WordText": "he's",
          },
           {
            "Height": 49,
            "Left": 1199,
            "Top": 2611,
            "Width": 192,
            "WordText": "moved",
          },
           {
            "Height": 41,
            "Left": 1416,
            "Top": 2620,
            "Width": 52,
            "WordText": "to",
          },
           {
            "Height": 57,
            "Left": 1490,
            "Top": 2614,
            "Width": 179,
            "WordText": "rehab,",
          },
           {
            "Height": 65,
            "Left": 1688,
            "Top": 2619,
            "Width": 344,
            "WordText": "somebody's",
          },
           {
            "Height": 48,
            "Left": 2052,
            "Top": 2638,
            "Width": 176,
            "WordText": "gonna",
          },
           {
            "Height": 49,
            "Left": 2252,
            "Top": 2624,
            "Width": 135,
            "WordText": "have",
          },
           {
            "Height": 40,
            "Left": 2408,
            "Top": 2633,
            "Width": 50,
            "WordText": "to",
          },
           {
            "Height": 50,
            "Left": 2481,
            "Top": 2625,
            "Width": 64,
            "WordText": "be",
          },
           {
            "Height": 49,
            "Left": 2567,
            "Top": 2626,
            "Width": 149,
            "WordText": "there",
          },
        ],
      },
       {
        "MaxHeight": 65,
        "MinTop": 2691,
        "Words":  [
           {
            "Height": 47,
            "Left": 278,
            "Top": 2691,
            "Width": 59,
            "WordText": "ali",
          },
           {
            "Height": 48,
            "Left": 359,
            "Top": 2693,
            "Width": 85,
            "WordText": "the",
          },
           {
            "Height": 47,
            "Left": 466,
            "Top": 2699,
            "Width": 134,
            "WordText": "time.",
          },
           {
            "Height": 65,
            "Left": 623,
            "Top": 2702,
            "Width": 156,
            "WordText": "Every",
          },
           {
            "Height": 64,
            "Left": 799,
            "Top": 2707,
            "Width": 162,
            "WordText": "single",
          },
           {
            "Height": 64,
            "Left": 981,
            "Top": 2712,
            "Width": 114,
            "WordText": "day.",
          },
        ],
      },
       {
        "MaxHeight": 70,
        "MinTop": 2863,
        "Words":  [
           {
            "Height": 49,
            "Left": 284,
            "Top": 2863,
            "Width": 194,
            "WordText": "BRIAN:",
          },
           {
            "Height": 70,
            "Left": 504,
            "Top": 2870,
            "Width": 277,
            "WordText": "Definitely.",
          },
        ],
      },
       {
        "MaxHeight": 58,
        "MinTop": 3030,
        "Words":  [
           {
            "Height": 52,
            "Left": 289,
            "Top": 3030,
            "Width": 205,
            "WordText": "PORKY:",
          },
           {
            "Height": 58,
            "Left": 516,
            "Top": 3039,
            "Width": 268,
            "WordText": "Whatever",
          },
           {
            "Height": 46,
            "Left": 805,
            "Top": 3053,
            "Width": 36,
            "WordText": "it",
          },
           {
            "Height": 52,
            "Left": 859,
            "Top": 3053,
            "Width": 160,
            "WordText": "takes.",
          },
        ],
      },
       {
        "MaxHeight": 48,
        "MinTop": 3200,
        "Words":  [
           {
            "Height": 48,
            "Left": 290,
            "Top": 3200,
            "Width": 107,
            "WordText": "LAN",
          },
           {
            "Height": 48,
            "Left": 408,
            "Top": 3205,
            "Width": 45,
            "WordText": "E:",
          },
           {
            "Height": 48,
            "Left": 477,
            "Top": 3209,
            "Width": 91,
            "WordText": "For",
          },
           {
            "Height": 37,
            "Left": 584,
            "Top": 3227,
            "Width": 132,
            "WordText": "sure.",
          },
        ],
      },
       {
        "MaxHeight": 65,
        "MinTop": 3371,
        "Words":  [
           {
            "Height": 56,
            "Left": 285,
            "Top": 3371,
            "Width": 194,
            "WordText": "JIMMY:",
          },
           {
            "Height": 54,
            "Left": 503,
            "Top": 3383,
            "Width": 84,
            "WordText": "Uh,",
          },
           {
            "Height": 57,
            "Left": 607,
            "Top": 3387,
            "Width": 166,
            "WordText": "shoot,",
          },
           {
            "Height": 65,
            "Left": 792,
            "Top": 3391,
            "Width": 143,
            "WordText": "okay,",
          },
           {
            "Height": 51,
            "Left": 954,
            "Top": 3397,
            "Width": 168,
            "WordText": "shoot.",
          },
        ],
      },
       {
        "MaxHeight": 60,
        "MinTop": 3537,
        "Words":  [
           {
            "Height": 60,
            "Left": 291,
            "Top": 3537,
            "Width": 222,
            "WordText": "DEBBIE:",
          },
           {
            "Height": 54,
            "Left": 535,
            "Top": 3553,
            "Width": 188,
            "WordText": "What's",
          },
           {
            "Height": 50,
            "Left": 744,
            "Top": 3575,
            "Width": 190,
            "WordText": "wrong.",
          },
        ],
      },
       {
        "MaxHeight": 57,
        "MinTop": 3704,
        "Words":  [
           {
            "Height": 55,
            "Left": 288,
            "Top": 3704,
            "Width": 193,
            "WordText": "JIMMY:",
          },
           {
            "Height": 55,
            "Left": 505,
            "Top": 3718,
            "Width": 78,
            "WordText": "Eli,",
          },
           {
            "Height": 46,
            "Left": 600,
            "Top": 3736,
            "Width": 99,
            "WordText": "you",
          },
           {
            "Height": 57,
            "Left": 720,
            "Top": 3733,
            "Width": 153,
            "WordText": "guys?",
          },
           {
            "Height": 49,
            "Left": 892,
            "Top": 3735,
            "Width": 102,
            "WordText": "You",
          },
           {
            "Height": 52,
            "Left": 1015,
            "Top": 3751,
            "Width": 140,
            "WordText": "guys,",
          },
           {
            "Height": 49,
            "Left": 1177,
            "Top": 3743,
            "Width": 77,
            "WordText": "for",
          },
           {
            "Height": 50,
            "Left": 1274,
            "Top": 3746,
            "Width": 86,
            "WordText": "the",
          },
           {
            "Height": 48,
            "Left": 1383,
            "Top": 3755,
            "Width": 213,
            "WordText": "record?",
          },
           {
            "Height": 46,
            "Left": 1619,
            "Top": 3760,
            "Width": 36,
            "WordText": "It",
          },
           {
            "Height": 50,
            "Left": 1675,
            "Top": 3762,
            "Width": 132,
            "WordText": "can't",
          },
           {
            "Height": 50,
            "Left": 1828,
            "Top": 3764,
            "Width": 65,
            "WordText": "be",
          },
           {
            "Height": 35,
            "Left": 1914,
            "Top": 3781,
            "Width": 97,
            "WordText": "rue.",
          },
        ],
      },
       {
        "MaxHeight": 57,
        "MinTop": 3869,
        "Words":  [
           {
            "Height": 57,
            "Left": 292,
            "Top": 3869,
            "Width": 61,
            "WordText": "F]:",
          },
           {
            "Height": 48,
            "Left": 377,
            "Top": 3875,
            "Width": 62,
            "WordText": "Be",
          },
           {
            "Height": 50,
            "Left": 458,
            "Top": 3883,
            "Width": 163,
            "WordText": "what?",
          },
        ],
      },
    ],
    "Message": "Total lines: 24",
  };

export default data; 